# Install and test and OMERO plugin e.g. a Web app, a CLI plugin or a library
#
# This workflow will install omero-test-infra, start an OMERO environment
# including database, server and web deployment, configure the OMERO plugin
# and run integration tests.
#
# 1. Set up the stage variable depending on the plugin. Supported stages
# are: app, cli, scripts, lib, srv
#
# 2. Adjust the cron schedule as necessary

name: OMERO

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  unit_test:
    name: Run unit tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version}}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install ".[tests]"
      - run: pytest test/unit

  lint:
    name: Run basic linting via pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version}}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install pre-commit
      - run: pre-commit run --all-files

  test:
    name: Run integration tests against OMERO
    runs-on: ubuntu-latest
    env:
      STAGE: cli
      PLUGIN: rdf
    steps:
      - uses: actions/checkout@v4
      - name: Checkout omero-test-infra
        uses: actions/checkout@master
        with:
          repository: ome/omero-test-infra
          path: .omero
          ref: ${{ secrets.OMERO_TEST_INFRA_REF }}
      - name: Build and run OMERO tests
        run: .omero/docker $STAGE
