# Install and test and OMERO plugin e.g. a Web app, a CLI plugin or a library
#
# This workflow will install omero-test-infra, start an OMERO environment
# including database, server and web deployment, configure the OMERO plugin
# and run integration tests.
#
# 1. Set up the stage variable depending on the plugin. Supported stages
# are: app, cli, scripts, lib, srv
#
# 2. Adjust the cron schedule as necessary

name: OMERO
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  unit_test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      # yamllint disable rule:line-length
      - run: pip install https://github.com/glencoesoftware/zeroc-ice-py-linux-x86_64/releases/download/20240202/zeroc_ice-3.6.5-cp311-cp311-manylinux_2_28_x86_64.whl
      # yamllint enable rule:line-length
      - run: pip install pytest
      - run: pip install .
      - run: pytest test/unit

  lint:
    name: Run basic linting via pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install pre-commit
      - run: pre-commit run --all-files
  test:
    name: Run integration tests against OMERO
    runs-on: ubuntu-latest
    env:
      STAGE: cli
      PLUGIN: rdf
    steps:
      - uses: actions/checkout@v4
      - name: Checkout omero-test-infra
        uses: actions/checkout@master
        with:
          repository: ome/omero-test-infra
          path: .omero
          ref: ${{ secrets.OMERO_TEST_INFRA_REF }}
      - name: Build and run OMERO tests
        run: .omero/docker $STAGE
